/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmck.PatientManagementSystem.Views;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Glenn McKnight
 */
public class AdminView extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8742853807095736824L;
	/**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titleJLabel = new javax.swing.JLabel();
        backgoundJTab = new javax.swing.JTabbedPane();
        homeJPanel = new javax.swing.JPanel();
        welcomeJLabel = new javax.swing.JLabel();
        detailsJLabel = new javax.swing.JLabel();
        detailsJPanel = new javax.swing.JPanel();
        userInfoJText = new javax.swing.JTextArea();
        messagesJLabel = new javax.swing.JLabel();
        deleteMessageJButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        messagesTable = new javax.swing.JTable();
        logoutJButton = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleJLabel.setText("Indisposed Clinic");

        welcomeJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcomeJLabel.setText("Welcome Back!");

        detailsJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        detailsJLabel.setText("Your details:");

        detailsJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        userInfoJText.setEditable(false);
        userInfoJText.setColumns(20);
        userInfoJText.setRows(5);

        javax.swing.GroupLayout detailsJPanelLayout = new javax.swing.GroupLayout(detailsJPanel);
        detailsJPanel.setLayout(detailsJPanelLayout);
        detailsJPanelLayout.setHorizontalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userInfoJText)
        );
        detailsJPanelLayout.setVerticalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userInfoJText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        messagesJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        messagesJLabel.setText("Messages");

        deleteMessageJButton.setText("Delete Message");

        messagesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(messagesTable);

        javax.swing.GroupLayout homeJPanelLayout = new javax.swing.GroupLayout(homeJPanel);
        homeJPanel.setLayout(homeJPanelLayout);
        homeJPanelLayout.setHorizontalGroup(
            homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(homeJPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeJPanelLayout.createSequentialGroup()
                        .addGroup(homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(detailsJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(homeJPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                                .addGroup(homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deleteMessageJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(58, 58, 58))
                    .addGroup(homeJPanelLayout.createSequentialGroup()
                        .addGroup(homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messagesJLabel)
                            .addComponent(detailsJLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        homeJPanelLayout.setVerticalGroup(
            homeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeJPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(welcomeJLabel)
                .addGap(18, 18, 18)
                .addComponent(detailsJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messagesJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteMessageJButton)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        welcomeJLabel.getAccessibleContext().setAccessibleName("Welcome Back");

        backgoundJTab.addTab("Home", homeJPanel);

        logoutJButton.setText("Log Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(titleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(logoutJButton)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgoundJTab))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 424, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 45, Short.MAX_VALUE)
                    .addComponent(backgoundJTab, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        userJPanel = new javax.swing.JPanel();
        removeUserJPanel = new javax.swing.JPanel();
        removeDocJCombo = new javax.swing.JComboBox<>();
        removeDoctorJLabel = new javax.swing.JLabel();
        removeDoctorJButton = new javax.swing.JButton();
        removeSecJButton = new javax.swing.JButton();
        removeSecJCombo = new javax.swing.JComboBox<>();
        removeSecJLabel = new javax.swing.JLabel();
        removeAdminJLabel = new javax.swing.JLabel();
        removeAdminJCombo = new javax.swing.JComboBox<>();
        removeAdminJButton = new javax.swing.JButton();
        removeUserJLabel = new javax.swing.JLabel();
        createUserJPanel = new javax.swing.JPanel();
        userTypeJCombo = new javax.swing.JComboBox<>();
        userTypeJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        userTitleJLabel = new javax.swing.JLabel();
        titleJCombo = new javax.swing.JComboBox<>();
        forenameJLabel = new javax.swing.JLabel();
        surnameJLabel = new javax.swing.JLabel();
        forenameJText = new javax.swing.JTextField();
        surnameJTextField = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();
        addressLine1Label = new javax.swing.JLabel();
        addressLine1JText = new javax.swing.JTextField();
        addressLine2Label1 = new javax.swing.JLabel();
        addressLine2JText = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityJText = new javax.swing.JTextField();
        postcodeLabel = new javax.swing.JLabel();
        postcodeJText = new javax.swing.JTextField();
        createUserJLabel = new javax.swing.JLabel();
        
                removeUserJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                
                        removeDoctorJLabel.setText("Remove Doctor:");
                        removeDoctorJLabel.setName(""); // NOI18N
                        
                                removeDoctorJButton.setText("Remove Doctor");
                                
                                        removeSecJButton.setText("Remove Secretary");
                                        
                                                removeSecJLabel.setText("Remove Secretary:");
                                                
                                                        removeAdminJLabel.setText("Remove Admin:");
                                                        
                                                                removeAdminJButton.setText("Remove Admin");
                                                                
                                                                        javax.swing.GroupLayout removeUserJPanelLayout = new javax.swing.GroupLayout(removeUserJPanel);
                                                                        removeUserJPanelLayout.setHorizontalGroup(
                                                                        	removeUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                        		.addGroup(removeUserJPanelLayout.createSequentialGroup()
                                                                        			.addContainerGap()
                                                                        			.addGroup(removeUserJPanelLayout.createParallelGroup(Alignment.TRAILING, false)
                                                                        				.addGroup(removeUserJPanelLayout.createSequentialGroup()
                                                                        					.addComponent(removeDoctorJLabel)
                                                                        					.addGap(27)
                                                                        					.addComponent(removeDocJCombo, GroupLayout.PREFERRED_SIZE, 340, GroupLayout.PREFERRED_SIZE))
                                                                        				.addGroup(removeUserJPanelLayout.createSequentialGroup()
                                                                        					.addGroup(removeUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                        						.addComponent(removeSecJLabel)
                                                                        						.addComponent(removeAdminJLabel))
                                                                        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        					.addGroup(removeUserJPanelLayout.createParallelGroup(Alignment.LEADING, false)
                                                                        						.addComponent(removeSecJCombo, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        						.addComponent(removeAdminJCombo, 0, 340, Short.MAX_VALUE))))
                                                                        			.addGroup(removeUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                        				.addGroup(removeUserJPanelLayout.createSequentialGroup()
                                                                        					.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                        					.addComponent(removeAdminJButton, GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                                                        				.addGroup(removeUserJPanelLayout.createSequentialGroup()
                                                                        					.addGap(10)
                                                                        					.addGroup(removeUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                        						.addComponent(removeSecJButton, GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                                                        						.addComponent(removeDoctorJButton, GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                                                                        			.addContainerGap())
                                                                        );
                                                                        removeUserJPanelLayout.setVerticalGroup(
                                                                        	removeUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                        		.addGroup(removeUserJPanelLayout.createSequentialGroup()
                                                                        			.addContainerGap()
                                                                        			.addGroup(removeUserJPanelLayout.createParallelGroup(Alignment.BASELINE)
                                                                        				.addComponent(removeDoctorJLabel)
                                                                        				.addComponent(removeDocJCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        				.addComponent(removeDoctorJButton))
                                                                        			.addGap(13)
                                                                        			.addGroup(removeUserJPanelLayout.createParallelGroup(Alignment.BASELINE)
                                                                        				.addComponent(removeSecJLabel)
                                                                        				.addComponent(removeSecJCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        				.addComponent(removeSecJButton))
                                                                        			.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                        			.addGroup(removeUserJPanelLayout.createParallelGroup(Alignment.BASELINE)
                                                                        				.addComponent(removeAdminJLabel)
                                                                        				.addComponent(removeAdminJCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        				.addComponent(removeAdminJButton))
                                                                        			.addContainerGap(24, Short.MAX_VALUE))
                                                                        );
                                                                        removeUserJPanel.setLayout(removeUserJPanelLayout);
                                                                        
                                                                                removeUserJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
                                                                                removeUserJLabel.setText("Remove User");
                                                                                
                                                                                        createUserJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                                                                                        
                                                                                                userTypeJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretary", "Doctor", "Administrator", " " }));
                                                                                                userTypeJCombo.addActionListener(new java.awt.event.ActionListener() {
                                                                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                                                        userTypeJComboActionPerformed(evt);
                                                                                                    }
                                                                                                });
                                                                                                
                                                                                                        userTypeJLabel.setText("User Type:");
                                                                                                        
                                                                                                                passwordJLabel.setText("Password:");
                                                                                                                
                                                                                                                        userTitleJLabel.setText("Title:");
                                                                                                                        
                                                                                                                                titleJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs.", "They" }));
                                                                                                                                
                                                                                                                                        forenameJLabel.setText("First Name:");
                                                                                                                                        
                                                                                                                                                surnameJLabel.setText("Surname:");
                                                                                                                                                
                                                                                                                                                        createJButton.setText("Create User");
                                                                                                                                                        
                                                                                                                                                                addressLine1Label.setText("Address Line 1:");
                                                                                                                                                                
                                                                                                                                                                        addressLine2Label1.setText("Address Line 2:");
                                                                                                                                                                        
                                                                                                                                                                                cityLabel.setText("City:");
                                                                                                                                                                                
                                                                                                                                                                                        postcodeLabel.setText("Postcode:");
                                                                                                                                                                                        
                                                                                                                                                                                                javax.swing.GroupLayout createUserJPanelLayout = new javax.swing.GroupLayout(createUserJPanel);
                                                                                                                                                                                                createUserJPanelLayout.setHorizontalGroup(
                                                                                                                                                                                                	createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                		.addGroup(createUserJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                			.addContainerGap()
                                                                                                                                                                                                			.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                				.addGroup(createUserJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                					.addComponent(userTypeJLabel)
                                                                                                                                                                                                					.addGap(31)
                                                                                                                                                                                                					.addComponent(userTypeJCombo, 0, 128, Short.MAX_VALUE)
                                                                                                                                                                                                					.addGap(73)
                                                                                                                                                                                                					.addComponent(addressLine1Label)
                                                                                                                                                                                                					.addGap(18)
                                                                                                                                                                                                					.addComponent(addressLine1JText, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                				.addGroup(createUserJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                					.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                						.addComponent(userTitleJLabel)
                                                                                                                                                                                                						.addComponent(forenameJLabel)
                                                                                                                                                                                                						.addComponent(surnameJLabel)
                                                                                                                                                                                                						.addComponent(passwordJLabel))
                                                                                                                                                                                                					.addGap(31)
                                                                                                                                                                                                					.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                						.addGroup(Alignment.TRAILING, createUserJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                							.addComponent(jPasswordField, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                							.addPreferredGap(ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                                                                                                                                                                                							.addComponent(createJButton))
                                                                                                                                                                                                						.addGroup(createUserJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                							.addComponent(surnameJTextField, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                							.addGap(40)
                                                                                                                                                                                                							.addComponent(postcodeLabel, GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                                                                                                                                                                                							.addGap(18)
                                                                                                                                                                                                							.addComponent(postcodeJText, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                						.addGroup(createUserJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                							.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                								.addComponent(titleJCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                								.addComponent(forenameJText, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                							.addPreferredGap(ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                                                                                                                                                                							.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                								.addComponent(cityLabel)
                                                                                                                                                                                                								.addComponent(addressLine2Label1))
                                                                                                                                                                                                							.addGap(18)
                                                                                                                                                                                                							.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                								.addComponent(addressLine2JText, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                								.addComponent(cityJText, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE))))))
                                                                                                                                                                                                			.addContainerGap())
                                                                                                                                                                                                );
                                                                                                                                                                                                createUserJPanelLayout.setVerticalGroup(
                                                                                                                                                                                                	createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                		.addGroup(createUserJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                			.addGap(9)
                                                                                                                                                                                                			.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                                                				.addComponent(userTypeJLabel)
                                                                                                                                                                                                				.addComponent(userTypeJCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                				.addComponent(addressLine1Label)
                                                                                                                                                                                                				.addComponent(addressLine1JText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                                                			.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                				.addGroup(createUserJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                					.addGap(1)
                                                                                                                                                                                                					.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                                                						.addComponent(titleJCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                						.addComponent(addressLine2Label1)
                                                                                                                                                                                                						.addComponent(addressLine2JText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                                                                				.addComponent(userTitleJLabel))
                                                                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                                                			.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                                                				.addComponent(forenameJText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                				.addComponent(forenameJLabel)
                                                                                                                                                                                                				.addComponent(cityLabel)
                                                                                                                                                                                                				.addComponent(cityJText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                                                			.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                                                				.addComponent(surnameJLabel)
                                                                                                                                                                                                				.addComponent(postcodeLabel)
                                                                                                                                                                                                				.addComponent(postcodeJText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                				.addComponent(surnameJTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                                                			.addGroup(createUserJPanelLayout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                                                				.addComponent(passwordJLabel)
                                                                                                                                                                                                				.addComponent(createJButton)
                                                                                                                                                                                                				.addComponent(jPasswordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                			.addContainerGap(25, Short.MAX_VALUE))
                                                                                                                                                                                                );
                                                                                                                                                                                                createUserJPanel.setLayout(createUserJPanelLayout);
                                                                                                                                                                                                
                                                                                                                                                                                                        addressLine1Label.getAccessibleContext().setAccessibleName("");
                                                                                                                                                                                                        
                                                                                                                                                                                                                createUserJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
                                                                                                                                                                                                                createUserJLabel.setText("Create User");
                                                                                                                                                                                                                
                                                                                                                                                                                                                        javax.swing.GroupLayout userJPanelLayout = new javax.swing.GroupLayout(userJPanel);
                                                                                                                                                                                                                        userJPanelLayout.setHorizontalGroup(
                                                                                                                                                                                                                        	userJPanelLayout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                                                                        		.addGroup(userJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                        			.addGap(22)
                                                                                                                                                                                                                        			.addGroup(userJPanelLayout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                                                                        				.addComponent(removeUserJPanel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                                                                                                                                                                                                                        				.addComponent(createUserJPanel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                                                                        				.addGroup(Alignment.LEADING, userJPanelLayout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                                                                        					.addGroup(userJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                        						.addComponent(removeUserJLabel)
                                                                                                                                                                                                                        						.addGap(535))
                                                                                                                                                                                                                        					.addGroup(userJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                        						.addComponent(createUserJLabel)
                                                                                                                                                                                                                        						.addGap(543))))
                                                                                                                                                                                                                        			.addGap(42))
                                                                                                                                                                                                                        );
                                                                                                                                                                                                                        userJPanelLayout.setVerticalGroup(
                                                                                                                                                                                                                        	userJPanelLayout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                                                                        		.addGroup(userJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                        			.addContainerGap(39, Short.MAX_VALUE)
                                                                                                                                                                                                                        			.addComponent(createUserJLabel)
                                                                                                                                                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                                                                        			.addComponent(createUserJPanel, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                        			.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                                                                                                                                                                        			.addComponent(removeUserJLabel)
                                                                                                                                                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                                                                        			.addComponent(removeUserJPanel, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                        			.addGap(5))
                                                                                                                                                                                                                        );
                                                                                                                                                                                                                        userJPanel.setLayout(userJPanelLayout);
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                backgoundJTab.addTab("Users", userJPanel);
                                                                                                                                                                                                                                doctorJPanel = new javax.swing.JPanel();
                                                                                                                                                                                                                                docRatingJCombo = new javax.swing.JComboBox<>();
                                                                                                                                                                                                                                docRatingJLabel = new javax.swing.JLabel();
                                                                                                                                                                                                                                docFeedbackLabel = new javax.swing.JLabel();
                                                                                                                                                                                                                                jScrollPane2 = new javax.swing.JScrollPane();
                                                                                                                                                                                                                                feedbackJText = new javax.swing.JTextArea();
                                                                                                                                                                                                                                sendFeedbackJButton = new javax.swing.JButton();
                                                                                                                                                                                                                                jScrollPane4 = new javax.swing.JScrollPane();
                                                                                                                                                                                                                                docRatingJList = new javax.swing.JList<>();
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                        docRatingJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
                                                                                                                                                                                                                                        docRatingJLabel.setText("Doctor Ratings");
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                docFeedbackLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
                                                                                                                                                                                                                                                docFeedbackLabel.setText("Doctor Feedback");
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                        feedbackJText.setColumns(20);
                                                                                                                                                                                                                                                        feedbackJText.setRows(5);
                                                                                                                                                                                                                                                        jScrollPane2.setViewportView(feedbackJText);
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                sendFeedbackJButton.setText("Send Feedback");
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                        jScrollPane4.setViewportView(docRatingJList);
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                javax.swing.GroupLayout doctorJPanelLayout = new javax.swing.GroupLayout(doctorJPanel);
                                                                                                                                                                                                                                                                                doctorJPanel.setLayout(doctorJPanelLayout);
                                                                                                                                                                                                                                                                                doctorJPanelLayout.setHorizontalGroup(
                                                                                                                                                                                                                                                                                    doctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                                                                                        .addContainerGap()
                                                                                                                                                                                                                                                                                        .addGroup(doctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                                                                                                                                            .addComponent(jScrollPane4)
                                                                                                                                                                                                                                                                                            .addComponent(docRatingJCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                                                                                                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, doctorJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                                                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                                                                                                                                                                                                                                                                                .addComponent(sendFeedbackJButton))
                                                                                                                                                                                                                                                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, doctorJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                                                                                                .addGroup(doctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                                                                                                                                                    .addComponent(docFeedbackLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                                                                                                    .addComponent(docRatingJLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                                                                                                                                                                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                                                                                                                                                                                                                                        .addContainerGap())
                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                doctorJPanelLayout.setVerticalGroup(
                                                                                                                                                                                                                                                                                    doctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                                                                                    .addGroup(doctorJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                                                                                        .addGap(19, 19, 19)
                                                                                                                                                                                                                                                                                        .addComponent(docRatingJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                                                                                                        .addComponent(docRatingJLabel)
                                                                                                                                                                                                                                                                                        .addGap(11, 11, 11)
                                                                                                                                                                                                                                                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                                                                                        .addGap(18, 18, 18)
                                                                                                                                                                                                                                                                                        .addComponent(docFeedbackLabel)
                                                                                                                                                                                                                                                                                        .addGroup(doctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                                                                                            .addGroup(doctorJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                                                                                                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                                                                                                            .addGroup(doctorJPanelLayout.createSequentialGroup()
                                                                                                                                                                                                                                                                                                .addGap(48, 48, 48)
                                                                                                                                                                                                                                                                                                .addComponent(sendFeedbackJButton)))
                                                                                                                                                                                                                                                                                        .addContainerGap(59, Short.MAX_VALUE))
                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        backgoundJTab.addTab("Doctor Info", doctorJPanel);

        pack();
    }// </editor-fold>                        

    private void userTypeJComboActionPerformed(java.awt.event.ActionEvent evt) {                                               
        setAddressFields();
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }
    /**
     * Display JOptionPane to notify the user when required.
     * @param message 
     */
    public void displayMessage(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    /**
     * Clear all JTextFields of user input.
     */
    public void clearCreateUserFields(){
        forenameJText.setText("");
        surnameJTextField.setText("");
        jPasswordField.setText("");
        addressLine1JText.setText("");
        addressLine2JText.setText("");
        cityJText.setText("");
        postcodeJText.setText("");
    }
    
    public void setAddressFields() {
    	if(getUserTypeJCombo() == "Doctor"){
            addressLine1JText.setEnabled(true);
            addressLine2JText.setEnabled(true);
            cityJText.setEnabled(true);
            postcodeJText.setEnabled(true);
            titleJCombo.setEnabled(false);
        }else{
        	addressLine1JText.setEnabled(false);
            addressLine2JText.setEnabled(false);
            cityJText.setEnabled(false);
            postcodeJText.setEnabled(false);
            titleJCombo.setEnabled(true);
        }
    }
    /**
     * Register logout button handler.
     * @param controller to respond to event.
     */
    public void addLogoutButtonHandler(ActionListener controller){
        logoutJButton.addActionListener(controller);
    }
    /**
   * Fills doctor JCombo with doctorIDs.
   * @param doctorIDs 
   */
  public void setDoctorCombo(List<String> doctorIDs){
  	removeDocJCombo.removeAllItems();
  	docRatingJCombo.removeAllItems();
  	
      doctorIDs.forEach((s) -> {
      	removeDocJCombo.addItem(s);
          docRatingJCombo.addItem(s);
      });
  }
    ////////////////////////////////////////////////////////////////////////////
    //Home Page   
    /**
     * Display logged in user details on home page.
     * @param info user details to be displayed.
     */
    public void setUserInfoJText(String info){
        this.userInfoJText.setText(info);
    }    
    /**
   * Set the messages the user has received to the messageTable.
   * @param messages of user to be displayed.
   */
  public void setUserMessages(String[] colNames, String[][] messages){
  	DefaultTableModel model = new DefaultTableModel(messages, colNames);
  	messagesTable.setModel(model);
  }
  /**
   * Register button handler to respond to delete message button.
   * @param controller to respond to delete message events.
   */
  public void addDeleteMessageButtonHandler(ActionListener controller){
      deleteMessageJButton.addActionListener(controller);
  }
  /**
   * Get the index of the selected message to be deleted.
   * @return 
   */
  public String getMessageToDelete(){
      int row = messagesTable.getSelectedRow();
      return messagesTable.getModel().getValueAt(row, 0).toString();
  } 
    ////////////////////////////////////////////////////////////////////////////
    //Users page    
    /**
     * Register button handler to respond to remove doctor button.
     * @param controller to respond to event.
     */
    public void addRemoveDoctorButtonHandler(ActionListener controller){
        removeDoctorJButton.addActionListener(controller);
    }
    /**
     * Register button handler to respond to remove secretary button.
     * @param controller  to respond to event.
     */
    public void addRemoveSecButtonHandler(ActionListener controller){
        removeSecJButton.addActionListener(controller);
    }
    /**
     * Register button handler to remove administrator button.
     * @param controller to respond to event.
     */
    public void addRemoveAdminButtonHandler(ActionListener controller){
        removeAdminJButton.addActionListener(controller);
    }
    /**
     * Register button handler to create user button.
     * @param controller to respond to event.
     */
    public void addCreateUserButtonHandler(ActionListener controller){
        createJButton.addActionListener(controller);
    }    
    /**
   * Get value from jpassword field of user creation.
   * @return password.
   */
	public char[] getjPasswordField() {
		return jPasswordField.getPassword();
	}
    /**
     * Get value from forename JTextField of user creation.
     * @return 
     */
    public String getForenameJText() {
        return forenameJText.getText();
    }
    /**
   * Get the value selected in the remove doctor JComboBox.
   * @return doctor to be removed.
   */
  public String getRemoveDocValue() {
      return removeDocJCombo.getSelectedItem().toString();
  }
  /**
   * Get the value selected in the remove secretary JComboBox.
   * @return secretary to be removed. 
   */
  public String getRemoveSecValue() {
      return removeSecJCombo.getSelectedItem().toString();
  }
  /**
   * Get the value selected in the remove administrator JComboBox.
   * @return administrator to be removed. 
   */
  public String getRemoveAdminValue(){
      return removeAdminJCombo.getSelectedItem().toString();
  }
    /**
     * Get value from surname JTextField of user creation.
     * @return surname.
     */
    public String getSurnameJTextField() {
        return surnameJTextField.getText();
    }
    /**
     * Get value from address line 1 JTextField of user creation.
     * @return address.
     */
    public String getAddressLine1Text(){
        return addressLine1JText.getText();
    }
    
    /**
     * Get value from address line 2 JTextField of user creation.
     * @return address.
     */
    public String getAddressLine2Text(){
        return addressLine2JText.getText();
    }
    
    /**
     * Get value from city JTextField of user creation.
     * @return address.
     */
    public String getCityText(){
        return cityJText.getText();
    }
    
    /**
     * Get value from postcode JTextField of user creation.
     * @return address.
     */
    public String getPostcodeText(){
        return postcodeJText.getText();
    }
    
    /**
     * Get value from title JTextBox of user creation.
     * @return user title.
     */
    public JComboBox<String> getTitleJCombo() {
        return titleJCombo;
    }
    /**
     * Get value from user type JTextBox of user creation.
     * @return type of user to be created.
     */
    public String getUserTypeJCombo() {
        return userTypeJCombo.getSelectedItem().toString();
    }    
    /**
//   * Sets value of remove secretary JCombo box.
//   * @param secretary list of secretaries.
//   */
  public void setSecCombo(List<String> secIDs) {
      removeSecJCombo.removeAllItems();
      
      secIDs.forEach((s) -> {
      	removeSecJCombo.addItem(s);
      });        
  }
  
  /**
   * Sets value of remove administrator JCombo box.
   * @param admin list of administrators.
   */
  public void setAdminCombo(List<String> adminIDs){
      removeAdminJCombo.removeAllItems();
      
      adminIDs.forEach((s) -> {
          removeAdminJCombo.addItem(s);
      }); 
  }
    
    ///////////////////////////////////////////////////////////////////////////
    //Doctor Info 
    /**
     * Register button handler to respond to doctor rating JCombo.
     * @param controller to respond to event.
     */
    public void addDoctorRatingJComboHandler(ActionListener controller){
        docRatingJCombo.addActionListener(controller);
    }
    /**
     * Get the information of the doctor selected in the combo box.
     * @return selected doctor.
     */
    public String getSelectedDoctor(){
        return docRatingJCombo.getSelectedItem().toString();
    }
    /**
     * Set the doctor rating JTextArea for each doctor in list.
     * @param ratings list of doctors and ratings to be set.
     */   
    public void setDoctorRatingsJText(String[] ratings){
        docRatingJList.setListData(ratings);
    }
    /**
     * Get inputted feedback to provide to a doctor. 
     * @return feedback text.
     */
    public String getDoctorFeedback(){
        return feedbackJText.getText();
    }
    
    /**
     * Clear all text from feedback Text area
     */
    public void clearFeedback() {
    	feedbackJText.setText("");
    }
    /**
     * Register button handler to respond to send feedback button.
     * @param controller to respond to event.
     */
    public void addSendFeedbackJButtonHandler(ActionListener controller){
        sendFeedbackJButton.addActionListener(controller);
    }
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JTextField addressLine1JText;
    private javax.swing.JLabel addressLine1Label;
    private javax.swing.JTextField addressLine2JText;
    private javax.swing.JLabel addressLine2Label1;
    private javax.swing.JTabbedPane backgoundJTab;
    private javax.swing.JTextField cityJText;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton createJButton;
    private javax.swing.JLabel createUserJLabel;
    private javax.swing.JPanel createUserJPanel;
    private javax.swing.JButton deleteMessageJButton;
    private javax.swing.JLabel detailsJLabel;
    private javax.swing.JPanel detailsJPanel;
    private javax.swing.JLabel docFeedbackLabel;
    private javax.swing.JComboBox<String> docRatingJCombo;
    private javax.swing.JLabel docRatingJLabel;
    private javax.swing.JList<String> docRatingJList;
    private javax.swing.JPanel doctorJPanel;
    private javax.swing.JTextArea feedbackJText;
    private javax.swing.JLabel forenameJLabel;
    private javax.swing.JTextField forenameJText;
    private javax.swing.JPanel homeJPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable messagesTable;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JLabel messagesJLabel;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JTextField postcodeJText;
    private javax.swing.JLabel postcodeLabel;
    private javax.swing.JButton removeAdminJButton;
    private javax.swing.JComboBox<Object> removeAdminJCombo;
    private javax.swing.JLabel removeAdminJLabel;
    private javax.swing.JComboBox<Object> removeDocJCombo;
    private javax.swing.JButton removeDoctorJButton;
    private javax.swing.JLabel removeDoctorJLabel;
    private javax.swing.JButton removeSecJButton;
    private javax.swing.JComboBox<Object> removeSecJCombo;
    private javax.swing.JLabel removeSecJLabel;
    private javax.swing.JLabel removeUserJLabel;
    private javax.swing.JPanel removeUserJPanel;
    private javax.swing.JButton sendFeedbackJButton;
    private javax.swing.JLabel surnameJLabel;
    private javax.swing.JTextField surnameJTextField;
    private javax.swing.JComboBox<String> titleJCombo;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JTextArea userInfoJText;
    private javax.swing.JPanel userJPanel;
    private javax.swing.JLabel userTitleJLabel;
    private javax.swing.JComboBox<String> userTypeJCombo;
    private javax.swing.JLabel userTypeJLabel;
    private javax.swing.JLabel welcomeJLabel;
    // End of variables declaration                   
}