/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmck.PatientManagementSystem.Views;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 * LoginView view class allows user to enter login details to access system or 
 * sign up for a new patient account.
 * @author Glenn McKnight
 */
public class LoginView extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3506648222986768776L;
	/**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        backgroundJTab = new javax.swing.JTabbedPane();
        loginJPanel = new javax.swing.JPanel();
        userIDJText = new javax.swing.JTextField();
        userIDJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        loginJButton = new javax.swing.JButton();
        signupJPanel = new javax.swing.JPanel();
        surnameJText = new javax.swing.JTextField();
        titleRegisterJLabel = new javax.swing.JLabel();
        forenameJLabel = new javax.swing.JLabel();
        forenameJText = new javax.swing.JTextField();
        surnameJLabel = new javax.swing.JLabel();
        titleJCombo = new javax.swing.JComboBox<>();
        ageJLabel = new javax.swing.JLabel();
        addressLine1Label = new javax.swing.JLabel();
        passwordRegisterJLabel = new javax.swing.JLabel();
        addressLine1Text = new javax.swing.JTextField();
        ageJText = new javax.swing.JTextField();
        passwordRegisterJText = new javax.swing.JPasswordField();
        signupJButton = new javax.swing.JButton();
        addressLine2Label = new javax.swing.JLabel();
        addressLine2JText = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        postcodeLabel = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        postcodeText = new javax.swing.JTextField();
        titleJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userIDJText.setName("jTextUsername"); // NOI18N

        userIDJLabel.setText("User ID:");
        userIDJLabel.setName("userIDJLabel"); // NOI18N

        passwordJLabel.setText("Password:");
        passwordJLabel.setName("passwordJLabel"); // NOI18N

        jPasswordField.setName(""); // NOI18N

        loginJButton.setText("Login");

        javax.swing.GroupLayout loginJPanelLayout = new javax.swing.GroupLayout(loginJPanel);
        loginJPanel.setLayout(loginJPanelLayout);
        loginJPanelLayout.setHorizontalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIDJLabel)
                    .addComponent(passwordJLabel))
                .addGap(54, 54, 54)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userIDJText)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        loginJPanelLayout.setVerticalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDJLabel))
                .addGap(23, 23, 23)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLabel)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginJButton)
                .addGap(111, 111, 111))
        );

        userIDJLabel.getAccessibleContext().setAccessibleName("userIDJLabel");

        backgroundJTab.addTab("Login", loginJPanel);

        titleRegisterJLabel.setText("Title: ");

        forenameJLabel.setText("Forename:");

        surnameJLabel.setText("Surname:");

        titleJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs.", "They" }));
        titleJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleJComboActionPerformed(evt);
            }
        });

        ageJLabel.setText("Age: ");

        addressLine1Label.setText("Address Line 1:");

        passwordRegisterJLabel.setText("Password: ");

        signupJButton.setText("Sign Up");

        addressLine2Label.setText("Address Line 2:");

        cityLabel.setText("City:");

        postcodeLabel.setText("Postcode:");

        javax.swing.GroupLayout signupJPanelLayout = new javax.swing.GroupLayout(signupJPanel);
        signupJPanel.setLayout(signupJPanelLayout);
        signupJPanelLayout.setHorizontalGroup(
            signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signupJPanelLayout.createSequentialGroup()
                        .addComponent(passwordRegisterJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signupJButton))
                    .addGroup(signupJPanelLayout.createSequentialGroup()
                        .addComponent(surnameJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(signupJPanelLayout.createSequentialGroup()
                        .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleRegisterJLabel)
                            .addComponent(forenameJLabel)
                            .addComponent(ageJLabel))
                        .addGap(54, 54, 54)
                        .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordRegisterJText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(signupJPanelLayout.createSequentialGroup()
                                .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ageJText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(forenameJText)
                                    .addComponent(surnameJText))
                                .addGap(50, 50, 50)
                                .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(signupJPanelLayout.createSequentialGroup()
                                        .addComponent(addressLine1Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(addressLine1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(signupJPanelLayout.createSequentialGroup()
                                        .addComponent(addressLine2Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addressLine2JText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(signupJPanelLayout.createSequentialGroup()
                                        .addComponent(postcodeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(postcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(signupJPanelLayout.createSequentialGroup()
                                        .addComponent(cityLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(21, 21, 21))
        );
        signupJPanelLayout.setVerticalGroup(
            signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupJPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signupJPanelLayout.createSequentialGroup()
                        .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleRegisterJLabel)
                            .addComponent(titleJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(forenameJLabel)
                            .addComponent(forenameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signupJPanelLayout.createSequentialGroup()
                        .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLine1Label)
                            .addComponent(addressLine1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLine2Label)
                            .addComponent(addressLine2JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameJLabel)
                    .addComponent(surnameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ageJLabel)
                        .addComponent(postcodeLabel)
                        .addComponent(postcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ageJText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signupJButton)
                        .addContainerGap())
                    .addGroup(signupJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(signupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordRegisterJLabel)
                            .addComponent(passwordRegisterJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );

        surnameJText.getAccessibleContext().setAccessibleName("surnameJLabel");
        titleRegisterJLabel.getAccessibleContext().setAccessibleName("titleRegisterJLabel");
        forenameJLabel.getAccessibleContext().setAccessibleName("ForenameJLabel");
        forenameJText.getAccessibleContext().setAccessibleName("forenameJText");
        surnameJLabel.getAccessibleContext().setAccessibleName("surnameJLabel");
        ageJLabel.getAccessibleContext().setAccessibleName("ageJLabel");
        addressLine1Label.getAccessibleContext().setAccessibleName("addressJLabel");
        passwordRegisterJLabel.getAccessibleContext().setAccessibleName("passwordRegisterJLabel");
        addressLine1Text.getAccessibleContext().setAccessibleName("addressJText");
        ageJText.getAccessibleContext().setAccessibleName("ageJText");

        backgroundJTab.addTab("Sign Up", signupJPanel);

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleJLabel.setText("Indisposed Clinic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJTab)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(titleJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundJTab, javax.swing.GroupLayout.PREFERRED_SIZE, 266, Short.MAX_VALUE))
        );

        backgroundJTab.getAccessibleContext().setAccessibleName("background");
        titleJLabel.getAccessibleContext().setAccessibleName("titleJLabel");

        pack();
    }// </editor-fold>                        

    private void titleJComboActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    /**
     * Displays a pop up error message using parameter text.
     * @param errorMessage error text to be displayed.
     */
    public void displayMessage(String errorMessage){
        JOptionPane.showMessageDialog(this, errorMessage);
    }
    
    /**
     * Add button handler controller to login button.
     * @param controller controller to listen for button event
     */
    public void addLoginButtonHandler(ActionListener controller){
        loginJButton.addActionListener(controller);
    }
     
    /**
     * Add button handler controller to sign up button.
     * @param controller controller to listen for button event.
     */
    public void addSignupButtonHandler(ActionListener controller){         
        signupJButton.addActionListener(controller);
    }
    /**
     * Get entered userID for login.
     * @return userID login.
     */
    public String getUserID(){         
        return userIDJText.getText();         
    }
    /**
     * Get enter jPassword for login.
     * @return login password.
     */
    public char[] getLoginPassword(){
    	char[] password = jPasswordField.getPassword();
    	jPasswordField.setText("");
    	return password;
    }
    /**
     * Get user title from signup page
     * @return user title.
     */
    public String getUserTitle(){
        return titleJCombo.getSelectedItem().toString();
    }
    /** 
     * Get user forename from sign up page.
     * @return user forename.
     */
    public String getForename(){
        return forenameJText.getText();
    }
    /** 
     * Get user surname from sign up page.
     * @return user surname.
     */
    public String getSurname(){
        return surnameJText.getText();
    }
    /** 
     * Get user age from sign up page. Parse to text.
     * @return user age.
     */
    public int getAge(){
        try{
            return Integer.parseInt(ageJText.getText());
        }catch(NumberFormatException ex){
            displayMessage("Enter a number for your age");
            throw new NumberFormatException();
        }         
    }
    /**
     * Get user addressLine1 from sign up page.
     * @return user address.
     */
    public String getAddressLine1(){
        return addressLine1Text.getText();
    }
    
    /**
     * Get user addressLine2 from sign up page.
     * @return user address.
     */
    public String getAddressLine2(){
        return addressLine2JText.getText();
    }
    
    /**
     * Get user city from sign up page.
     * @return user address.
     */
    public String getCity(){
        return cityText.getText();
    }
    
    /**
     * Get user postcode from sign up page.
     * @return user address.
     */
    public String getPostcode(){
        return postcodeText.getText();
    }
    
    /** 
     * Get user password from sign up page.
     * @return sign up password.
     */
    public char[] getSignupPassword(){
        return passwordRegisterJText.getPassword();
    }
    /**
     * Clear fields of user sign up page so another user can request account.
     */
    public void clearFields(){
        ageJText.setText("");
        forenameJText.setText("");
        surnameJText.setText("");
        addressLine1Text.setText("");
        passwordRegisterJText.setText("");
        jPasswordField.setText("");
        addressLine1Text.setText("");
        addressLine2JText.setText("");
        cityText.setText("");
        postcodeText.setText("");
    }
     
    // Variables declaration - do not modify                     
    private javax.swing.JLabel addressLine1Label;
    private javax.swing.JTextField addressLine1Text;
    private javax.swing.JTextField addressLine2JText;
    private javax.swing.JLabel addressLine2Label;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JTextField ageJText;
    private javax.swing.JTabbedPane backgroundJTab;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JLabel forenameJLabel;
    private javax.swing.JTextField forenameJText;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JButton loginJButton;
    private javax.swing.JPanel loginJPanel;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JLabel passwordRegisterJLabel;
    private javax.swing.JPasswordField passwordRegisterJText;
    private javax.swing.JLabel postcodeLabel;
    private javax.swing.JTextField postcodeText;
    private javax.swing.JButton signupJButton;
    private javax.swing.JPanel signupJPanel;
    private javax.swing.JLabel surnameJLabel;
    private javax.swing.JTextField surnameJText;
    private javax.swing.JComboBox<String> titleJCombo;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel titleRegisterJLabel;
    private javax.swing.JLabel userIDJLabel;
    private javax.swing.JTextField userIDJText;
    // End of variables declaration                   
}
